on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Obter a ultima versão
        uses: actions/checkout@v4

      - name: 📂 Sincronizar os arquivos
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ftp.webvoluntarios.kinghost.net
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
